linting code updates

diff --git a/.github/workflows/code-linting-pr.yml b/.github/workflows/code-linting-pr.yml
--- a/.github/workflows/code-linting-pr.yml
+++ b/.github/workflows/code-linting-pr.yml
@@ -1,28 +1,8 @@
 name: Lint code for syntax issues on pull requests
 
-on:
-  pull_request:
+on: pull_request
 
 jobs:
-  # lint-inspec-all:
-  #   runs-on: ubuntu-22.04
-  #   steps:
-  #     - name: Clone Repo
-  #       uses: actions/checkout@v4
-  #     - name: Install System Dependencies
-  #       run: |
-  #         sudo apt-get update
-  #         sudo apt-get install -y \
-  #           ruby ruby-dev \
-  #           git curl build-essential libffi-dev libssl-dev zlib1g-dev libreadline-dev libyaml-dev
-  #     - name: Install Inspec and cookstyle
-  #       run: |
-  #         gem install inspec cookstyle
-  #     - name: Run Rubocop with Custom Config
-  #       run: |
-  #         echo "Running rubocop with custom config"
-  #         rubocop --config .rubocop.yml .
-
   lint-inspec-all:
     runs-on: ubuntu-latest
     container:
@@ -35,20 +15,19 @@ jobs:
         run: |
           rubocop --config .rubocop.yml .
 
-  ansiblelint-aria-lcm-v1r2-srg:
+  list-ansible-repos:
     runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.matrix.outputs.value }}
     steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
+      - uses: actions/checkout@v4
+      - name: Get Ansible Repo List
+        id: matrix
         run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd aria/lifecycle/8.x/v1r2-srg/ansible/vmware-vrslcm-8.x-stig-ansible-hardening/
-          ansible-lint .
+          echo "value=$(find . -name '*-stig-ansible-*' -printf '%P\n' | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
 
-  ansiblelint-aria-logs-v1r4-srg:
+  run-ansible-lint:
+    needs: list-ansible-repos
     runs-on: ubuntu-latest
     steps:
       - name: Clone Repo
@@ -58,226 +37,24 @@ jobs:
           pip3 install ansible ansible-lint
       - name: Run ansible-lint
         run: |
-          cd aria/operations-for-logs/8.x/v1r4-srg/ansible/vmware-vrli-8.x-stig-ansible-hardening/
-          ansible-lint .
+          echo "rootdir = $(pwd)"
+          for prj in ${{ join(fromJSON(needs.list-ansible-repos.outputs.matrix), ' ') }}
+            do
+              echo " "
+              echo "**********************************************************************************************************************"
+              echo " RUNNING ansible-lint on"
+              echo "/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/$prj"
+              echo "----------------------------------------------------------------------------------------------------------------------"
+              cd "/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/$prj"
+              ansible-lint . --offline || command_failed=1
+              echo "**********************************************************************************************************************"
+            done
 
-  ansiblelint-aria-ops-v1r2-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd aria/operations/8.x/v1r2-srg/ansible/vmware-aria-operations-8x-stig-ansible-hardening/
-          ansible-lint .
+          if [ ${command_failed:-0} -eq 1 ]
+          then
+            echo "************ LINTING ERROR(S) OCCURRED ***********"
+            exit 1
+          fi
 
-  ansiblelint-nsx3-v1r3-stig:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd nsx/3.x/v1r3-stig/ansible/vmware-nsxt-3.x-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-nsx4-v1r1-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd nsx/4.x/v1r1-srg/ansible/vmware-nsx-4.x-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-nsx4-v1r2-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd nsx/4.x/v1r2-srg/ansible/vmware-nsx-4.x-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-nsx4-v1r1-stig:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd nsx/4.x/v1r1-stig/ansible/vmware-nsx-4.x-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-photon3-v1r9-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd photon/3.0/v1r9-srg/ansible/vmware-photon-3.0-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-photon4-v1r5-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd photon/4.0/v1r5-srg/ansible/vmware-photon-4.0-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-photon5-v1r3-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd photon/5.0/v1r3-srg/ansible/vmware-photon-5.0-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-photon5-v2r1-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd photon/5.0/v2r1-srg/ansible/vmware-photon-5.0-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-vcd10x-v1r1-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd vcd/10.x/v1r1-srg/ansible/vmware-cloud-director-10.x-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-vcf5x-v1r1-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd vcf/5.x/v1r1-srg/ansible/vmware-cloud-foundation-sddcmgr-5x-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-vcf5x-v1r2-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd vcf/5.x/v1r2-srg/ansible/vmware-cloud-foundation-sddcmgr-5x-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-vcf5x-v1r3-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd vcf/5.x/v1r3-srg/ansible/vmware-cloud-foundation-sddcmgr-5x-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-vsphere70:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd vsphere/7.0/v1r3-stig/vcsa/ansible/vmware-vcsa-7.0-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-vsphere80-v1r1-srg:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd vsphere/8.0/v2r1-stig/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-vsphere80-v1r1-stig:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd vsphere/8.0/v1r1-stig/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/
-          ansible-lint .
-
-  ansiblelint-vsphere80-v2r1-stig:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Repo
-        uses: actions/checkout@v4
-      - name: Install Ansible and ansible-lint
-        run: |
-          pip3 install ansible ansible-lint
-      - name: Run ansible-lint
-        run: |
-          cd vsphere/8.0/v2r1-stig/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/
-          ansible-lint .
+          echo "************ SUCCESS *****************"
+          exit 0
